//! The replication slot is bound to a **catalog epoch**; losing it resets every shape (ADR-0004).
//!
//! Upstream creates the slot at boot if it is missing and never looks at it again. A slot lost to a
//! restore-from-backup, `max_slot_wal_keep_size`, a major upgrade or an operator is then silently
//! recreated *at the current WAL head* — and every shape quietly misses the span of changes between
//! the old slot's `confirmed_flush_lsn` and that head, with no signal anywhere.
//!
//! So the engine records which slot, in which cluster, it is bound to. The first time it creates
//! (or adopts) its slot it appends a [`SlotBinding`] to the durable catalog as
//! `CatalogEvent::SlotBound`; the last such event in the log **is** the current epoch. Before every
//! connection — at boot and on every ingestor reconnect, not just at boot — the slot is verified
//! against that binding ([`verdict`]).
//!
//! ## What breaks an epoch, and what does not
//!
//! An **epoch break** is a slot the engine can no longer trust: it is gone, its WAL is `lost`, it is
//! there under a different output plugin (so it is somebody else's slot wearing our name), or the
//! cluster's `system_identifier` is not the one the binding names. The only correct recovery is a
//! new slot and a full resync of every shape — there is no way to fill the gap.
//!
//! Two things that look similar and are **not** breaks:
//!
//! - a slot held by another walsender (`active` with an `active_pid`): Postgres allows exactly one,
//!   so this is a second engine on the same slot, or our own predecessor that Postgres has not yet
//!   reaped. The engine waits (and says so) rather than tearing anything down;
//! - a `timeline_id` that moved. It is recorded and logged, never acted on: the first deployment has
//!   one primary and no promotion (ADR-0004 defers failover handling).
//!
//! ## The two policies
//!
//! `ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS` (default `true`) picks between them:
//!
//! - **auto-reset** (Electric parity, the default): [`Engine::reset_epoch`] retires every shape —
//!   active and dormant alike, each stream closed then deleted (ADR-0007) with a `Dropped` record —
//!   drops and recreates the slot, and appends a new `SlotBound`. That binding IS the new epoch.
//!   Clients see closed streams and re-subscribe. An unattended deployment self-heals, at the cost
//!   of an unscheduled backfill storm;
//! - **refuse** (`=false`): the engine enters a named degraded state, ingest does not start, and
//!   every shape route answers 503. Recovery is a deliberate human act: `POST /epoch/reset` runs
//!   exactly the same reset and clears the degradation.
//!
//! Both go through the one [`Engine::reset_epoch`], serialised by a lock plus a generation counter,
//! so a second concurrent caller waits and then finds the epoch already rebound rather than
//! resetting twice.

use super::*;

use crate::pg::SlotObservation;
use crate::replication::Refused;

/// `ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS`, default `true`. Anything that spells "off" selects the
/// refuse policy; everything else (including a value nobody meant) keeps the safe-by-default
/// self-healing behaviour.
fn auto_reset_from_env() -> bool {
    match std::env::var("ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS") {
        Ok(v) => !matches!(v.trim().to_ascii_lowercase().as_str(), "0" | "false" | "off" | "no"),
        Err(_) => true,
    }
}

/// How long a reset waits for the catalog writer at each of its two barriers. Long enough to ride out
/// a storage hiccup, short enough that a wedged writer is reported rather than hung on.
const CATALOG_DRAIN_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);

/// Clears the `resetting` flag however the reset ends — including the early `bail!` at the first
/// drain barrier, and a panic. A flag left set would refuse every create for the life of the
/// process.
struct ResettingGuard(Arc<EpochState>);

impl ResettingGuard {
    fn new(epoch: Arc<EpochState>) -> Self {
        ResettingGuard(epoch)
    }
}

impl Drop for ResettingGuard {
    fn drop(&mut self) {
        self.0.resetting.store(false, Ordering::SeqCst);
    }
}

/// One binding of the engine to a replication slot: the cluster it belongs to, the slot name, and
/// when the binding was made. Written to the durable catalog as `SlotBound` and folded back at boot
/// — the last one in the log is the epoch every shape in that catalog belongs to.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct SlotBinding {
    /// `pg_control_system().system_identifier` — generated by `initdb`, so it distinguishes a
    /// restore-from-backup (or an entirely different cluster at the same URL) from the cluster the
    /// engine's shapes were built from.
    pub system_identifier: String,
    /// `pg_control_checkpoint().timeline_id` at binding time. Recorded, never acted on.
    pub timeline_id: u32,
    pub slot: String,
    /// The server clock (ISO-8601 UTC) when the epoch started.
    pub bound_at: String,
}

/// Why an epoch broke. The strings are the wire form (`GET /replication/lsn` → `epoch.reason`) and
/// are part of the operator contract, so they are spelled once, here.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EpochBreakReason {
    /// The slot is not there — or what is there is not ours (a different output plugin).
    SlotLost,
    /// `pg_replication_slots.wal_status = 'lost'`: the WAL the slot needed has been removed.
    SlotWalLost,
    /// A different Postgres cluster answers at this URL than the one the epoch was bound in.
    SystemIdentifierMismatch,
}

impl EpochBreakReason {
    pub fn as_str(self) -> &'static str {
        match self {
            EpochBreakReason::SlotLost => "slot_lost",
            EpochBreakReason::SlotWalLost => "slot_wal_lost",
            EpochBreakReason::SystemIdentifierMismatch => "system_identifier_mismatch",
        }
    }
}

impl std::fmt::Display for EpochBreakReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The engine is refusing every shape read and create because its epoch broke and the policy is
/// `ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS=false`.
///
/// A typed error for the same reason [`Degraded`] is one: the HTTP layer maps it to 503 by downcast,
/// never by matching message text. It is deliberately **not** `Degraded` — that latch means "lost
/// membership effects, restart required" and drives the subquery stream reaper, whereas this one is
/// cleared in place by an operator's `POST /epoch/reset` and destroys nothing until they ask.
#[derive(Debug)]
pub struct EpochBroken {
    pub reason: EpochBreakReason,
}

impl std::fmt::Display for EpochBroken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "epoch broken ({}): the replication slot is no longer the one the engine bound to, so every \
             shape is missing an unknown span of changes; POST /epoch/reset starts a new epoch",
            self.reason
        )
    }
}

impl std::error::Error for EpochBroken {}

/// A reset is in flight: the shapes are being retired and the slot replaced, so nothing may register
/// against the epoch on its way out. Retryable in a moment, unlike [`EpochBroken`] — hence its own
/// type, mapped to the same 503.
#[derive(Debug)]
pub struct EpochResetting;

impl std::fmt::Display for EpochResetting {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("epoch reset in progress; retry")
    }
}

impl std::error::Error for EpochResetting {}

/// What the engine should do about the slot it just observed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum Verdict {
    /// No `SlotBound` in the catalog: a genuine first boot. Create-or-adopt the slot and record the
    /// binding.
    FirstBoot,
    /// The bound epoch is intact — stream. `timeline_changed` is reported, not acted on.
    Ok { timeline_changed: bool },
    /// Someone else's walsender holds the slot. Not a break: wait for it.
    Busy { active_pid: Option<i32> },
    /// The slot cannot be trusted; the epoch is over.
    Break(EpochBreakReason),
}

/// The verdict, as a pure function of what Postgres reports and what the catalog remembers — so
/// every branch of the policy is a unit test rather than a Postgres you have to break by hand.
pub(crate) fn verdict(obs: &SlotObservation, bound: Option<&SlotBinding>) -> Verdict {
    // Nothing in the catalog names an epoch, so there is nothing to be inconsistent with. This is
    // the ONLY path that may create a slot from nothing.
    let Some(bound) = bound else { return Verdict::FirstBoot };
    // The cluster is the outer container: a different one makes every other observation moot (its
    // slot of the same name would be a coincidence, not ours).
    if bound.system_identifier != obs.system_identifier {
        return Verdict::Break(EpochBreakReason::SystemIdentifierMismatch);
    }
    let Some(slot) = obs.slot.as_ref() else {
        return Verdict::Break(EpochBreakReason::SlotLost);
    };
    // A slot under another output plugin is not the slot we bound: ours was dropped and something
    // else took the name.
    if slot.plugin.as_deref() != Some(crate::pg::PGOUTPUT) {
        return Verdict::Break(EpochBreakReason::SlotLost);
    }
    // The slot survives but the WAL it needed does not (`max_slot_wal_keep_size`), which is the same
    // hole by another route.
    if slot.wal_status.as_deref() == Some("lost") {
        return Verdict::Break(EpochBreakReason::SlotWalLost);
    }
    if slot.active && slot.active_pid.is_some() {
        return Verdict::Busy { active_pid: slot.active_pid };
    }
    Verdict::Ok { timeline_changed: bound.timeline_id != obs.timeline_id }
}

/// Everything the engine holds about its epoch.
pub(crate) struct EpochState {
    /// The slot name this engine runs on, learned from `setup_postgres` (`None` in library mode).
    slot: std::sync::Mutex<Option<String>>,
    /// The binding the engine is currently operating under: the catalog's last `SlotBound`, or the
    /// one this process wrote.
    binding: std::sync::Mutex<Option<SlotBinding>>,
    /// Set when the epoch broke under the refuse policy; cleared by a reset. This is the whole
    /// degraded state — there is no second latch.
    broken: std::sync::Mutex<Option<EpochBreakReason>>,
    /// Serialises [`Engine::reset_epoch`].
    reset_lock: tokio::sync::Mutex<()>,
    /// Bumped by every completed rebind. A caller captures it *before* taking `reset_lock`, so a
    /// second concurrent reset wakes up, sees it moved, and returns — one break, one new epoch.
    generation: std::sync::atomic::AtomicU64,
    /// True from the moment a reset enumerates the shapes it will retire until the new epoch is
    /// bound and durable. Set inside the engine-state critical section that does the enumeration, so
    /// a create is either in that enumeration or refused — never in between.
    resetting: std::sync::atomic::AtomicBool,
    /// Cuts the ingestor's reconnect backoff short when the epoch is rebound.
    wake: tokio::sync::Notify,
    /// `ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS`, read once at construction.
    auto_reset: bool,
}

impl EpochState {
    pub(crate) fn new() -> Arc<Self> {
        Arc::new(EpochState {
            slot: std::sync::Mutex::new(None),
            binding: std::sync::Mutex::new(None),
            broken: std::sync::Mutex::new(None),
            reset_lock: tokio::sync::Mutex::new(()),
            generation: std::sync::atomic::AtomicU64::new(0),
            resetting: std::sync::atomic::AtomicBool::new(false),
            wake: tokio::sync::Notify::new(),
            auto_reset: auto_reset_from_env(),
        })
    }
}

impl Engine {
    /// Which slot this engine runs on (`None` before `setup_postgres`, and in library mode).
    pub(crate) fn epoch_slot(&self) -> Option<String> {
        self.epoch.slot.lock().unwrap().clone()
    }

    /// Record the slot name; called once, early in `setup_postgres`, before any verification.
    pub(crate) fn set_epoch_slot(&self, slot: &str) {
        *self.epoch.slot.lock().unwrap() = Some(slot.to_string());
    }

    /// The binding the engine is operating under.
    pub fn epoch_binding(&self) -> Option<SlotBinding> {
        self.epoch.binding.lock().unwrap().clone()
    }

    /// Install the folded catalog's last `SlotBound` as the engine's binding (boot).
    pub(crate) fn adopt_epoch_binding(&self, binding: Option<SlotBinding>) {
        *self.epoch.binding.lock().unwrap() = binding;
    }

    /// `Some(reason)` while the epoch is broken: latched the moment a break is detected, under
    /// EITHER policy, and cleared only by a rebind. Under the refuse policy that is the whole
    /// degraded state (every shape route answers 503, `/v1/health` says `degraded`); under
    /// auto-reset it is the "a reset is owed here" flag, so a reset that fails part-way is retried
    /// on the next connection attempt instead of being forgotten.
    pub fn epoch_broken(&self) -> Option<EpochBreakReason> {
        *self.epoch.broken.lock().unwrap()
    }

    /// Is a reset running right now? Every create/join/snapshot takes this gate under the
    /// engine-state lock (see `Engine::ensure_not_degraded`).
    pub fn epoch_resetting(&self) -> bool {
        self.epoch.resetting.load(Ordering::SeqCst)
    }

    /// Is the configured policy auto-reset (the default)?
    pub(crate) fn epoch_auto_reset(&self) -> bool {
        self.epoch.auto_reset
    }

    /// The `epoch` object on `GET /replication/lsn` — what an operator (and the consumer's health
    /// check) reads to tell "healthy" from "waiting for me".
    pub fn epoch_json(&self) -> serde_json::Value {
        let broken = self.epoch_broken();
        let b = self.epoch_binding();
        serde_json::json!({
            "state": if broken.is_some() { "broken" } else { "ok" },
            "reason": broken.map(EpochBreakReason::as_str),
            "systemIdentifier": b.as_ref().map(|b| b.system_identifier.clone()),
            "timelineId": b.as_ref().map(|b| b.timeline_id),
            "slot": b.as_ref().map(|b| b.slot.clone()),
            "boundAt": b.as_ref().map(|b| b.bound_at.clone()),
        })
    }

    /// Latch the break, and count + announce it **once**.
    ///
    /// The latch is what makes the count right: a reset that fails is retried on every reconnect,
    /// and each retry re-derives the same verdict — `epoch_breaks_total` must stay "epochs that
    /// ended", not "times we noticed". Returns whether this call is the one that latched it.
    pub(crate) fn latch_epoch_break(&self, reason: EpochBreakReason, slot: &str) -> bool {
        let mut broken = self.epoch.broken.lock().unwrap();
        if broken.is_some() {
            return false;
        }
        *broken = Some(reason);
        drop(broken);
        crate::metrics::metrics().epoch_breaks.fetch_add(1, Ordering::Relaxed);
        tracing::error!(
            "EPOCH BREAK on slot '{slot}' ({reason}): the slot the engine bound to is not the slot \
             postgres has, so every shape is missing an unknown span of changes and no amount of \
             replaying can fill it"
        );
        true
    }

    /// Say, once, that the refuse policy is in force and what clears it.
    pub(crate) fn log_refuse_policy(&self, reason: EpochBreakReason) {
        tracing::error!(
            "ELECTRIC_CIRCUITS_RESET_ON_SLOT_LOSS=false: ingest is stopped and every shape route \
             answers 503 (reason '{reason}'). POST /epoch/reset to retire every shape, bind a new \
             epoch and resume."
        );
    }

    /// Read the cluster identity, append a `SlotBound` and adopt it. This — not the
    /// `pg_create_logical_replication_slot` call — is what starts an epoch.
    async fn bind_epoch(&self, client: &tokio_postgres::Client, slot: &str) -> Result<SlotBinding> {
        let id = crate::pg::cluster_identity(client).await?;
        let binding = SlotBinding {
            system_identifier: id.system_identifier,
            timeline_id: id.timeline_id,
            slot: slot.to_string(),
            bound_at: id.now_iso,
        };
        self.catalog_tx.send(CatalogEvent::SlotBound(binding.clone()));
        *self.epoch.binding.lock().unwrap() = Some(binding.clone());
        *self.epoch.broken.lock().unwrap() = None;
        self.epoch.generation.fetch_add(1, Ordering::SeqCst);
        tracing::info!(
            "epoch bound: slot '{slot}' on cluster {} (timeline {}) at {}",
            binding.system_identifier,
            binding.timeline_id,
            binding.bound_at
        );
        // An operator reset is answered by the ingestor at once rather than after up to 30s of
        // backoff.
        self.epoch.wake.notify_one();
        Ok(binding)
    }

    /// Boot-time verification (ADR-0004 step B). Runs on the setup connection, before anything is
    /// restored, and — on the first-boot verdict — is what creates and records the slot.
    pub(crate) async fn verify_epoch_at_boot(
        &self,
        client: &tokio_postgres::Client,
        slot: &str,
    ) -> Result<Verdict> {
        let obs = crate::pg::observe_slot(client, slot).await?;
        let v = verdict(&obs, self.epoch_binding().as_ref());
        match &v {
            Verdict::FirstBoot => {
                // Nothing in the catalog claims an epoch: create the slot, or adopt one an operator
                // pre-created, and record which it is. One thing is never adopted — a slot whose WAL
                // is already gone. There is nothing to salvage (no shapes exist yet) and adopting it
                // would start a brand new deployment in a state its very first reconnect declares
                // broken.
                if obs.slot.as_ref().is_some_and(|s| s.wal_status.as_deref() == Some("lost")) {
                    tracing::warn!(
                        "slot '{slot}' already exists with wal_status 'lost' and no epoch claims it; \
                         recreating it rather than starting a fresh deployment on a dead slot"
                    );
                    crate::pg::recreate_slot(client, slot).await?;
                } else {
                    crate::pg::ensure_slot(client, slot).await?;
                }
                self.bind_epoch(client, slot).await?;
            }
            Verdict::Ok { timeline_changed } => {
                if *timeline_changed {
                    self.warn_timeline_changed(&obs);
                }
            }
            Verdict::Busy { active_pid } => tracing::warn!(
                "slot '{slot}' is held by walsender pid {:?}: another engine is on this slot. The \
                 epoch itself is intact — this engine will keep retrying the connection.",
                active_pid
            ),
            Verdict::Break(_) => {}
        }
        Ok(v)
    }

    fn warn_timeline_changed(&self, obs: &SlotObservation) {
        let was = self.epoch_binding().map(|b| b.timeline_id).unwrap_or(0);
        tracing::warn!(
            "postgres timeline changed ({was} -> {}) since this epoch was bound. The system \
             identifier still matches, so the epoch stands and this is recorded only — failover \
             handling is deferred (ADR-0004).",
            obs.timeline_id
        );
    }

    /// End the current epoch and start a new one — the single reset, used by the auto policy (boot
    /// and reconnect) and by `POST /epoch/reset`.
    ///
    /// The order is what makes it crash-safe, and every step is fenced by the one before it:
    ///
    /// 1. **enumerate + fence.** The shapes to retire are snapshotted in one engine-state critical
    ///    section, which also bumps `EngineState::epoch_gen` and raises the `resetting` flag. A
    ///    create is therefore either inside that snapshot (retired here, then rolled back by its own
    ///    closing check) or refused outright — never installed with a backfill snapshot older than
    ///    the slot that is about to replace it;
    /// 2. **retire**, then **drain the `Dropped` records to storage**. This drain is a *barrier*, not
    ///    a courtesy: once the new slot exists, a crash with `Created` records still queued leaves a
    ///    catalog whose last binding is the OLD epoch and whose shapes were never dropped — the next
    ///    boot would Resume-restore them straight over the gap. A drain that does not complete aborts
    ///    the reset with the break still latched, so it is retried rather than half-done;
    /// 3. **recreate the slot**, then **bind** — the new `SlotBound` is what makes the epoch real,
    ///    and the break stays latched until it is written, so a failure in between cannot leave the
    ///    engine streaming a fresh slot under the old binding;
    /// 4. **drain again**, and only then consider the circuit-tier restart: exiting with the
    ///    `SlotBound` still queued would be the very crash step 2 exists to prevent.
    pub async fn reset_epoch(&self, reason: EpochBreakReason) -> Result<()> {
        // Captured BEFORE the lock: whoever wins rebinds, and everyone behind them finds the
        // generation moved and returns into the epoch that winner created.
        let seen = self.epoch.generation.load(Ordering::SeqCst);
        let _guard = self.epoch.reset_lock.lock().await;
        if self.epoch.generation.load(Ordering::SeqCst) != seen {
            tracing::info!("epoch reset: another caller already bound the new epoch; nothing to do");
            return Ok(());
        }
        let url = self.pg_url.clone().context("epoch reset requires postgres mode")?;
        let slot = self.epoch_slot().context("epoch reset before the engine knows its slot")?;
        // Latched for the whole reset (a retry of a half-finished one finds it already latched, so
        // this neither double-counts nor re-announces). Cleared by `bind_epoch`, i.e. only once the
        // new epoch is on the log.
        self.latch_epoch_break(reason, &slot);
        // Cleared on every exit path, including the early returns below — a stuck `resetting` flag
        // would refuse every create for the life of the process.
        let _resetting = ResettingGuard::new(self.epoch.clone());

        // 1. Enumerate EVERY shape — active and dormant, plain, aggregate and subquery. None of them
        //    can be brought up to date: the gap is in the WAL, not in anything the engine holds. The
        //    generation bump and the `resetting` flag are raised in the same critical section, which
        //    is what closes the create race (see the doc comment).
        let ids: Vec<String> = {
            let mut st = self.state.lock().await;
            self.epoch.resetting.store(true, Ordering::SeqCst);
            st.epoch_gen += 1;
            st.shapes.keys().cloned().collect()
        };
        tracing::error!(
            "epoch reset ({reason}) on slot '{slot}': retiring {} shape(s) and binding a new epoch; \
             clients must re-subscribe and will backfill from postgres",
            ids.len()
        );
        // `purge_shape` closes each stream before deleting it (ADR-0007), so a client tailing one is
        // released at once with `stream-closed` instead of waiting on a stream nothing will ever
        // append to again, and writes `Dropped` so the restore cannot resurrect it.
        for id in &ids {
            if let Err(e) = self.purge_shape(id).await {
                tracing::error!("epoch reset: retiring shape {id} failed: {e:#}");
            }
        }

        // 2. The barrier. Nothing may create the new slot until every `Dropped` is durable.
        if !self.catalog_tx.drain(CATALOG_DRAIN_TIMEOUT).await {
            bail!(
                "epoch reset: the catalog writer did not drain the shape drops within {:?}, so the \
                 new slot must not be created yet (a crash would leave old-epoch shapes beside the \
                 old binding). The epoch stays broken and the reset will be retried.",
                CATALOG_DRAIN_TIMEOUT
            );
        }

        // 3. A brand new slot, then the binding that makes it an epoch. Whatever is there now (a slot
        //    of the same name someone else made, a slot whose WAL is gone) is not ours, so it is
        //    dropped rather than adopted. A dedicated connection, never the shared pool: the pool is
        //    where the post-reset backfill storm queues, and the reset must not wait behind it.
        let client = crate::pg::connect(&url).await.context("epoch reset: connect to postgres")?;
        crate::pg::recreate_slot(&client, &slot).await?;
        // From here until `bind_epoch` succeeds the slot exists but nothing records it. The break is
        // still latched, so a failure here leaves the engine refusing (and, under the auto policy,
        // retrying) rather than streaming a fresh slot under the old binding.
        self.bind_epoch(&client, &slot).await?;
        drop(client);
        // Counted here, not on entry: `epoch_resets_total` is "new epochs bound", so an attempt that
        // aborted at the drain barrier and was retried must not show up as two.
        crate::metrics::metrics().epoch_resets.fetch_add(1, Ordering::Relaxed);

        // 4. The new epoch must be durable before anything acts on it.
        let drained = self.catalog_tx.drain(CATALOG_DRAIN_TIMEOUT).await;
        if !drained {
            tracing::error!(
                "epoch reset: the new SlotBound has not reached storage within {CATALOG_DRAIN_TIMEOUT:?}. \
                 The engine is running in the new epoch, but a crash before the write lands would \
                 leave the durable catalog naming the old one."
            );
        }

        // The counts pipelines were seeded from a snapshot on the far side of the gap and have no
        // runtime rebuild, so — exactly as for schema drift on a circuit-served table (ADR-0005) —
        // the process restarts and boot re-seeds them. Only reachable after boot: at boot the reset
        // runs before the circuit is built. Never with a drain outstanding: exiting then would
        // destroy the very records that make the new epoch restorable.
        if self.arrangements.lock().unwrap().is_some() {
            if !drained {
                tracing::error!(
                    "epoch reset: NOT restarting for the counts pipelines, because the catalog writer \
                     has not drained — the restart would lose those records. The circuit's counts are \
                     stale (they predate the gap); restart the engine once storage is healthy."
                );
                return Ok(());
            }
            tracing::error!(
                "epoch reset with counts pipelines running: the circuit was seeded before the gap and \
                 has no runtime rebuild, so its counts no longer describe the tables. Restarting the \
                 process (exit {}): boot re-seeds the circuit in the new epoch.",
                super::drift::EXIT_CIRCUIT_REBUILD
            );
            std::process::exit(super::drift::EXIT_CIRCUIT_REBUILD);
        }
        Ok(())
    }

    /// Apply the configured policy to a break. Shared by the boot check and the ingestor's
    /// pre-connect check, so both count, announce and act identically.
    pub(crate) async fn on_epoch_break(
        &self,
        reason: EpochBreakReason,
        slot: &str,
    ) -> std::result::Result<(), Refused> {
        let first = self.latch_epoch_break(reason, slot);
        if !self.epoch_auto_reset() {
            if first {
                self.log_refuse_policy(reason);
            }
            return Err(Refused::EpochBroken(reason.as_str()));
        }
        match self.reset_epoch(reason).await {
            Ok(()) => Ok(()),
            Err(e) => {
                // The reset itself failed (postgres went away mid-reset, the catalog writer did not
                // drain). The break stays latched, so the next attempt resumes it; never connect to a
                // slot whose epoch has not been re-established.
                tracing::error!("epoch reset failed: {e:#}; the epoch stays broken and will be retried");
                Err(Refused::CheckFailed)
            }
        }
    }
}

impl Engine {
    /// Run the reset's engine-state critical section — enumerate, bump the epoch generation, raise
    /// the `resetting` flag — with no Postgres round trip, and hold the flag until the returned
    /// handle is dropped. Test-only: it is what a create racing a real reset actually sees.
    #[doc(hidden)]
    pub async fn force_epoch_reset_window(&self) -> EpochResetWindow {
        let mut st = self.state.lock().await;
        self.epoch.resetting.store(true, Ordering::SeqCst);
        st.epoch_gen += 1;
        drop(st);
        EpochResetWindow(ResettingGuard::new(self.epoch.clone()))
    }
}

/// Keeps a simulated epoch reset "in flight" until dropped (see [`Engine::force_epoch_reset_window`]).
#[doc(hidden)]
pub struct EpochResetWindow(#[allow(dead_code)] ResettingGuard);

/// The ingestor's gate on the connection itself (see [`crate::replication::EpochEvents`]).
impl crate::replication::EpochEvents for Engine {
    fn before_connect(&self) -> crate::replication::BoxFuture<'_, std::result::Result<(), Refused>> {
        Box::pin(async move {
            let (Some(url), Some(slot)) = (self.pg_url.clone(), self.epoch_slot()) else {
                return Ok(()); // library mode has no slot to verify
            };
            // Already latched broken. Under the refuse policy only an operator clears it, and the
            // check below would just re-derive what we know. Under auto-reset it means a reset was
            // owed and did not finish — resume it rather than re-observing a slot whose verdict may
            // now look `Ok` (the new slot exists) while the catalog still names the old epoch.
            if let Some(reason) = self.epoch_broken() {
                return self.on_epoch_break(reason, &slot).await;
            }
            // A dedicated connection, not the shared pool: the pool is where shape backfills queue,
            // and the one check that decides whether ingest may resume must never wait behind them.
            let client = match crate::pg::connect(&url).await {
                Ok(c) => c,
                Err(e) => {
                    tracing::warn!("epoch check: postgres unreachable ({e:#})");
                    return Err(Refused::CheckFailed);
                }
            };
            let obs = match crate::pg::observe_slot(&client, &slot).await {
                Ok(o) => o,
                Err(e) => {
                    tracing::warn!("epoch check: could not read the slot ({e:#})");
                    return Err(Refused::CheckFailed);
                }
            };
            drop(client);
            match verdict(&obs, self.epoch_binding().as_ref()) {
                // Boot binds the epoch before the ingestor is spawned, so this is only reachable if
                // the catalog write is still in flight; connecting is correct either way.
                Verdict::FirstBoot => Ok(()),
                Verdict::Ok { timeline_changed } => {
                    if timeline_changed {
                        self.warn_timeline_changed(&obs);
                    }
                    Ok(())
                }
                Verdict::Busy { active_pid } => Err(Refused::SlotBusy(active_pid)),
                Verdict::Break(reason) => self.on_epoch_break(reason, &slot).await,
            }
        })
    }

    fn epoch_rebound(&self) -> crate::replication::BoxFuture<'_, ()> {
        Box::pin(async move { self.epoch.wake.notified().await })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pg::SlotRow;

    fn binding() -> SlotBinding {
        SlotBinding {
            system_identifier: "7300000000000000001".to_string(),
            timeline_id: 1,
            slot: "electric_circuits".to_string(),
            bound_at: "2026-08-21T10:00:00.000Z".to_string(),
        }
    }

    /// A healthy, idle slot in the cluster the epoch was bound in.
    fn healthy() -> SlotObservation {
        SlotObservation {
            system_identifier: binding().system_identifier,
            timeline_id: 1,
            slot: Some(SlotRow {
                active: false,
                active_pid: None,
                wal_status: Some("reserved".to_string()),
                confirmed_flush_lsn: Some("0/1A2B3C".to_string()),
                plugin: Some("pgoutput".to_string()),
            }),
        }
    }

    /// No `SlotBound` anywhere in the catalog means nobody has claimed an epoch yet — the ONLY
    /// verdict allowed to create a slot from nothing. A slot that already exists is adopted, not
    /// treated as somebody else's.
    #[test]
    fn an_empty_catalog_is_a_first_boot() {
        assert_eq!(verdict(&healthy(), None), Verdict::FirstBoot);
        let mut obs = healthy();
        obs.slot = None;
        assert_eq!(verdict(&obs, None), Verdict::FirstBoot);
    }

    /// The ordinary case: slot present, plugin ours, WAL reserved, same cluster.
    #[test]
    fn a_matching_slot_proceeds() {
        assert_eq!(verdict(&healthy(), Some(&binding())), Verdict::Ok { timeline_changed: false });
    }

    /// The case upstream misses entirely: the slot is simply gone. Recreating it at the current head
    /// would leave every shape short of the intervening changes, so this ends the epoch.
    #[test]
    fn a_missing_slot_breaks_the_epoch() {
        let mut obs = healthy();
        obs.slot = None;
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Break(EpochBreakReason::SlotLost));
    }

    /// A slot of the right name under a different output plugin is somebody else's slot wearing our
    /// name — ours was dropped, which is the same hole.
    #[test]
    fn a_foreign_plugin_breaks_the_epoch() {
        let mut obs = healthy();
        obs.slot.as_mut().unwrap().plugin = Some("test_decoding".to_string());
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Break(EpochBreakReason::SlotLost));
    }

    /// `wal_status = 'lost'` (`max_slot_wal_keep_size` did its job): the slot object survives, the
    /// WAL behind it does not, and the gap is exactly as unfillable.
    #[test]
    fn a_lost_wal_status_breaks_the_epoch() {
        let mut obs = healthy();
        obs.slot.as_mut().unwrap().wal_status = Some("lost".to_string());
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Break(EpochBreakReason::SlotWalLost));
        // The other statuses are all fine — only `lost` is terminal.
        for status in ["reserved", "extended", "unreserved"] {
            let mut obs = healthy();
            obs.slot.as_mut().unwrap().wal_status = Some(status.to_string());
            assert_eq!(
                verdict(&obs, Some(&binding())),
                Verdict::Ok { timeline_changed: false },
                "wal_status '{status}' is not a break"
            );
        }
        // …and a server too old to report it at all (pre-PG13) is not a break either.
        let mut obs = healthy();
        obs.slot.as_mut().unwrap().wal_status = None;
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Ok { timeline_changed: false });
    }

    /// A different cluster answering at the same URL — a restore from backup, or a connection string
    /// repointed. The identifier is checked FIRST: with the cluster wrong, everything else about the
    /// slot is a coincidence.
    #[test]
    fn a_different_cluster_breaks_the_epoch() {
        let mut obs = healthy();
        obs.system_identifier = "7300000000000000002".to_string();
        assert_eq!(
            verdict(&obs, Some(&binding())),
            Verdict::Break(EpochBreakReason::SystemIdentifierMismatch)
        );
        // Even when the slot itself is also gone, the cluster is the more informative cause.
        obs.slot = None;
        assert_eq!(
            verdict(&obs, Some(&binding())),
            Verdict::Break(EpochBreakReason::SystemIdentifierMismatch)
        );
    }

    /// Another walsender on the slot is NOT a break: postgres allows exactly one, and the second
    /// engine (or our own not-yet-reaped predecessor) going away fixes it. Tearing every shape down
    /// over it would be catastrophic and wrong.
    #[test]
    fn a_foreign_walsender_is_not_a_break() {
        let mut obs = healthy();
        obs.slot.as_mut().unwrap().active = true;
        obs.slot.as_mut().unwrap().active_pid = Some(4242);
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Busy { active_pid: Some(4242) });

        // A genuine break outranks it: a `lost` slot held by someone else is still lost.
        obs.slot.as_mut().unwrap().wal_status = Some("lost".to_string());
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Break(EpochBreakReason::SlotWalLost));
    }

    /// A timeline change is recorded and logged, never acted on (single primary — ADR-0004): the
    /// verdict still proceeds.
    #[test]
    fn a_changed_timeline_only_reports() {
        let mut obs = healthy();
        obs.timeline_id = 2;
        assert_eq!(verdict(&obs, Some(&binding())), Verdict::Ok { timeline_changed: true });
    }

    /// The reason strings are the operator contract (`/replication/lsn` → `epoch.reason`), so they
    /// are pinned rather than left to a Debug rename.
    #[test]
    fn the_break_reasons_have_stable_names() {
        assert_eq!(EpochBreakReason::SlotLost.as_str(), "slot_lost");
        assert_eq!(EpochBreakReason::SlotWalLost.as_str(), "slot_wal_lost");
        assert_eq!(EpochBreakReason::SystemIdentifierMismatch.as_str(), "system_identifier_mismatch");
    }
}
